version: '3.9'

services:
  worker:
    build:
        context: ./worker
        dockerfile: Dockerfile.dev
    depends_on:
      - redis
    environment:
      - QUEUE_HOST=redis
      - WORKER_CONCURRENCY=20   
  redis:
    image: redis:7
    ports:
      - "6379:6379"