version: '3.9'

services:
  notify-api:
    build:
      context: ./api
    ports:
      - "3000:3000"
    depends_on:
      - redis
    environment:
      - QUEUE_HOST=redis

  worker:
    build:
        context: ./worker
    depends_on:
      - redis
    environment:
      - QUEUE_HOST=redis
  redis:
    image: redis:7
    ports:
      - "6379:6379"